# Generated by Django 5.2.9 on 2026-03-06 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEEDS', 'Seeds / Heritage Seeds'), ('FERT', 'Organic Fertilizer'), ('CROP', 'Surplus Harvest'), ('OTHER', 'Other')], default='CROP', max_length=10)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity_str', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_exchange', models.BooleanField(default=False)),
                ('location_tag', models.CharField(db_index=True, max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('seed_guardian', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
